Add the option to run the unit test 'testcluster' in release mode

diff --git a/testcluster b/testcluster
--- a/testcluster
+++ b/testcluster
@@ -1,5 +1,56 @@
 #!/bin/bash
 #source venv/bin/activate && python manage.py test authome --keepdb
+if [[ "$1" == "" ]]
+then
+    mode="debug"
+elif [[ "$1" == "release" ]]
+then
+    mode="release"
+else
+    mode="debug"
+fi
+if [[ "$mode" == "release" ]]
+then
+    echo "Running in release mode"
+    echo "Backup the source code via renaming authome to authome.bak"
+    mv -v authome authome.bak
+    if [[ "$?" != "0" ]]
+    then
+        echo "Failed to rename authome to authome.bak"
+        exit 1 
+    fi
+    echo "Get the test code via copying authome.bak to authome"
+    cp -rvf authome.bak authome
+    if [[ "$?" != "0" ]]
+    then
+        echo "Failed to copy authome.bak to authome"
+        exit 1 
+    fi
+    cd authome
+    echo "prepare the test code via comment out the debug.log, Debug.log and performance related code"
+    find ./ -type f -iname '*.py' -exec sed -i 's/logger\.debug/#logger.debug/g' "{}" +;
+    find ./ -type f -iname '*.py' -exec sed -i 's/from \. import performance/#from . import performance/g' "{}" +;
+    find ./ -type f -iname '*.py' -exec sed -i 's/from \.\. import performance/#from .. import performance/g' "{}" +;
+    find ./ -type f -iname '*.py' -exec sed -i 's/performance\.start_processingstep/#performance.start_processingstep/g' "{}" +;
+    find ./ -type f -iname '*.py' -exec sed -i 's/performance\.end_processingstep/#performance.end_processingstep/g' "{}" +;
+
+    find ./ -type f -iname '*.py' -exec sed -i 's/from \.models import DebugLog/#from .models import DebugLog/g' "{}" +;
+    find ./ -type f -iname '*.py' -exec sed -i 's/from \.\.models import DebugLog/#from ..models import DebugLog/g' "{}" +;
+    find ./ -type f -iname '*.py' -exec sed -i 's/DebugLog\.log/#DebugLog.log/g' "{}" +;
+    find ./ -type f -iname '*.py' -exec sed -i 's/DebugLog\.attach_request/#DebugLog.attach_request/g' "{}" +;
+
+    cd ..
+else
+    echo "Running in debug mode"
+fi
+echo "Running unit test"
 TEST_RUNNER=authome.testrunners.NoDatabaseTestRunner
 export TEST_RUNNER
 export IGNORE_LOADING_ERROR=True ; poetry run python manage.py test authome --keepdb --pattern="testcluster.py"
+if [[ "$mode" == "release" ]]
+then
+    echo "remove the test code"
+    rm -rf authome
+    echo "Recovery the source code vi renameing authome.bak to authome"
+    mv -v authome.bak authome
+fi
